// <auto-generated />
using System;
using LibrAI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibrAI.Migrations
{
    [DbContext(typeof(LibrAiDbContext))]
    [Migration("20250922001906_LoansInit")]
    partial class LoansInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("LibrAI.Data.Entities.Book", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("author")
                        .HasColumnType("TEXT")
                        .HasColumnName("author");

                    b.Property<string>("description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("image_url")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<string>("isbn")
                        .HasColumnType("TEXT")
                        .HasColumnName("isbn");

                    b.Property<string>("language")
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<int?>("page_count")
                        .HasColumnType("INTEGER")
                        .HasColumnName("page_count");

                    b.Property<string>("price")
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<string>("publish_date")
                        .HasColumnType("TEXT")
                        .HasColumnName("publish_date");

                    b.Property<string>("publisher")
                        .HasColumnType("TEXT")
                        .HasColumnName("publisher");

                    b.Property<string>("title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("id");

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("LibrAI.Data.Entities.Publisher", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("image_url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("id");

                    b.ToTable("publishers", (string)null);
                });

            modelBuilder.Entity("LibrAI.Features.Books.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("book_id");

                    b.Property<DateTime>("BorrowedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("borrowed_at");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("due_at");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("returned_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .HasDatabaseName("IX_loans_book");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_loans_user");

                    b.ToTable("loans", (string)null);
                });

            modelBuilder.Entity("LibrAI.Features.Books.Loan", b =>
                {
                    b.HasOne("LibrAI.Data.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });
#pragma warning restore 612, 618
        }
    }
}
